---

- set_fact:
    collateral_ok_count: 0

- include_role:
    name: mn-find-collateral
  vars:
    masternode: '{{ masternodes[item] }}'
    masternode_name: '{{ item }}'
    find_protx: '{{ use_protx }}'
  with_items: '{{ groups["masternodes"] }}'

- name: fail if not all collaterals are ok
  fail:
    msg: "could not find collateral"
  when: collateral_ok_count|int != groups["masternodes"]|length

- set_fact:
    net_subdir: ""
- name: set net_subdir for non-mainnet nodes
  set_fact:
    net_subdir: "/{{ axe_network }}"
  when: axe_network != "mainnet"
- name: append devnet name to net_subdir
  set_fact:
    net_subdir: "{{ net_subdir }}-{{ axe_devnet_name }}"
  when: axe_network == "devnet"

- debug: var=net_subdir

- name: create masternode.conf
  template:
    src: 'masternode.conf.j2'
    dest: '{{ axed_home }}/.axecore{{ net_subdir }}/masternode.conf'
    owner: '{{ axed_user }}'
    group: '{{ axed_group }}'
    mode: '0640'
  register: masternode_config_state

- name: restart axed
  command: docker restart axed
  when: masternode_config_state.changed
