---

- name: ensure /etc/docker exists
  file: path=/etc/docker state=directory mode='0700' owner='root' group='root'

- name: create daemon.json
  template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0640'
  register: daemon_json_state

- name: update systemd service
  become: true
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
  loop:
    - "docker.service"
    - "docker.socket"
  register: daemon_systemd_state

- name: update upstart defaults
  become: true
  copy:
    src: docker
    dest: /etc/default/

- name: restart docker
  service:
    name: docker
    state: restarted
    daemon_reload: true
  when: daemon_json_state is changed or daemon_systemd_state is changed
