- name: Add the official OpenVPN APT key
  apt_key:
    url:  https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present

- name: Add the official OpenVPN repository
  apt_repository:
    repo: 'deb https://build.openvpn.net/debian/openvpn/stable {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes

- name: Prepare list of forwared IPs
  vars:
    openvpn_forwarded_ips: []
  set_fact:
    openvpn_forwarded_ips: "{{ openvpn_forwarded_ips }} + [ 'route {{ hostvars[item].public_ip }} 255.255.255.255' ]"
  when: item != "vpn"
  loop: "{{ groups['all'] }}"

- name: Setup OpenVPN
  include_role:
    name: kyl191.openvpn
  vars:
    clients:
    - "{{ axe_network_name }}"
    openvpn_client_register_dns: no
    openvpn_server_hostname: "{{ public_ip }}"
    openvpn_set_dns: false
    openvpn_push: "[ 'route-nopull' ] + {{openvpn_forwarded_ips}}"
    openvpn_redirect_gateway: no

- name: Copy OpenVPN config to 'netwoks' dir
  become: no
  vars:
    openvpn_config_path: "/tmp/ansible/{{ axe_network_name }}/{{inventory_hostname}}.ovpn"
  local_action: "copy src={{ openvpn_config_path }} dest=../networks/{{ axe_network_name }}.ovpn"
