---

- name: disable pay-faucet
  systemd:
    name: 'pay-faucet'
    state: stopped
    enabled: False
  failed_when: False

- name: disable axed-generate-miner
  systemd:
    name: 'axed-generate-miner'
    state: stopped
    enabled: False
  failed_when: False

- name: kill all docker containers
  shell: if [ -n "$(docker ps -qa)" ]; then docker rm -fv $(docker ps -qa); fi

- name: remove all docker volumes
  shell: docker volume ls -qf dangling=true | xargs -r docker volume rm

- name: remove all docker images
  shell: docker image ls -q | xargs -r docker image rm

- name: delete axe home dir
  file:
      state: absent
      path: "{{ axed_home }}/"
